version: '3.0'

services:
  mariadb:
    image: mariadb:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=123456

    volumes:
      - ./create-databases.sql:/docker-entrypoint-initdb.d/setup.sql

  listener:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile

    volumes:
      - ../configs/testing.cfg:/code/configs/production.cfg

    env_file:
      - test.env
    depends_on:
      - mariadb
